### ISSUE TITLE
gRPC Python 不支持 details 不支持 Unicode

### ISSUE THREAD

**Issue by earlzo** [shanbay/sea#102]
[Python grpc doesn't handle unicode inside an exception message #11442](https://github.com/grpc/grpc/issues/11442)

因此 sea 的 RpcException 实现会导致出现非 ASCII 字符时产生错误, 同时客户端收到 Internal Server Error 错误.

```Python
class RpcException(Exception):

    code = None
    details = None

    def __init__(self, message=None, *args, **kwargs):
        if isinstance(message, (list, dict)):
            message = json.dumps(
                message, default=str, ensure_ascii=False)
        if not isinstance(message, str):
            message = str(message)
        if message is not None:
            self.details = message
        super().__init__(message, *args, **kwargs)
```

另外我尝试使用 metadata 发送 Unicode 内容, 但同样是不行的.
因此如果需要传送 Unicode 内容时, 可以将 Unicode 字符串转义为 ASCII, 具体做法是使`json.dumps` 的 `ensure_ascii=True`, 对于一般字符串, 可以调用`json.encoder.py_encode_basestring_ascii` 对Unicode字符串进行转义. 

或者用 base64 之类的方法进行编码.

此类方法需要调用端做响应的配合, 加大了 client 和 server 的 耦合程度.

**Comment by earlzo** [comment]
服务端验证代码:
```Python
...
from json.encoder import py_encode_basestring_ascii

class FairyCourseServicer(fairy_course_pb2_grpc.FairyCourseServicer, metaclass=ServicerMeta):
    def CreateLevel(self, request, context):
        data = msg2dict(request)
        level = models.Level.create(data)
        return fairy_course_pb2.Level(**level.attributes_to_dict())

    def DeleteLevel(self, request, context):
        # set metadata
        # mt = [('foo', '我真的好饿'), ('bar', '中午吃麻辣烫')]
        # context.send_initial_metadata(mt)
        # raise NotDeletable('哎呀真的不能删的啦')
        raise NotDeletable(py_encode_basestring_ascii('哎呀真的不能删的啦'))
...
```
客户端验证代码
```Python
import sys

sys.path.insert(0, '/opt/proj/shanbay/backend/fairy/protos')
import grpc

import base_pb2
import fairy_course_pb2_grpc


def run():
    channel = grpc.insecure_channel('localhost:6000')
    stub = fairy_course_pb2_grpc.FairyCourseStub(channel)
    try:
        res = stub.DeleteLevel(base_pb2.IdReq())
        print(res.initial_metadata())
    except grpc.RpcError as e:
        print(e, e.code(), e.details(), e.details().encode().decode('unicode-escape'))
        raise


if __name__ == '__main__':
    run()
```

输出结果:

```
<_Rendezvous of RPC that terminated with (StatusCode.FAILED_PRECONDITION, "\u54ce\u5440\u771f\u7684\u4e0d\u80fd\u5220\u7684\u5566")> StatusCode.FAILED_PRECONDITION "\u54ce\u5440\u771f\u7684\u4e0d\u80fd\u5220\u7684\u5566" "哎呀真的不能删的啦"
Traceback (most recent call last):
  File "proof.py", line 22, in <module>
    run()
  File "proof.py", line 14, in run
    res = stub.DeleteLevel(base_pb2.IdReq())
  File "/home/ubuntu/miniconda3/envs/shanbay-rpc-3.5/lib/python3.5/site-packages/grpc/_channel.py", line 492, in __call__
    return _end_unary_response_blocking(state, call, False, deadline)
  File "/home/ubuntu/miniconda3/envs/shanbay-rpc-3.5/lib/python3.5/site-packages/grpc/_channel.py", line 440, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.FAILED_PRECONDITION, "\u54ce\u5440\u771f\u7684\u4e0d\u80fd\u5220\u7684\u5566")>
```

**Comment by earlzo** [comment]
另外这个问题应该是 gRPC 为了考虑 Python2 和 Python3 兼容性而做的妥协, 官方似乎也不打算进一步支持, 相关的 issue 已被关闭, 其他语言并没有发现这个问题. 

以 Go 语言为例.

服务端代码
```Go
package main

import (
	"log"
	"net"

	"golang.org/x/net/context"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	pb "google.golang.org/grpc/examples/helloworld/helloworld"
	"google.golang.org/grpc/reflection"
)

const (
	port = ":50051"
)

// server is used to implement helloworld.GreeterServer.
type server struct{}

// SayHello implements helloworld.GreeterServer
func (s *server) SayHello(ctx context.Context, in *pb.HelloRequest) (*pb.HelloReply, error) {
	// return &pb.HelloReply{Message: "Hello " + in.Name}, nil
	return nil, grpc.Errorf(codes.InvalidArgument, "我会说中国话")
}

func main() {
	lis, err := net.Listen("tcp", port)
	if err != nil {
		log.Fatalf("failed to listen: %v", err)
	}
	s := grpc.NewServer()
	pb.RegisterGreeterServer(s, &server{})
	// Register reflection service on gRPC server.
	reflection.Register(s)
	if err := s.Serve(lis); err != nil {
		log.Fatalf("failed to serve: %v", err)
	}
}
```

客户端代码
```Go
package main

import (
	"log"
	"os"

	"golang.org/x/net/context"
	"google.golang.org/grpc"
	pb "google.golang.org/grpc/examples/helloworld/helloworld"
)

const (
	address     = "localhost:50051"
	defaultName = "world"
)

func main() {
	// Set up a connection to the server.
	conn, err := grpc.Dial(address, grpc.WithInsecure())
	if err != nil {
		log.Fatalf("did not connect: %v", err)
	}
	defer conn.Close()
	c := pb.NewGreeterClient(conn)

	// Contact the server and print out its response.
	name := defaultName
	if len(os.Args) > 1 {
		name = os.Args[1]
	}
	r, err := c.SayHello(context.Background(), &pb.HelloRequest{Name: name})
	if err != nil {
		log.Fatalf("could not greet: %v", err)
	}
	log.Printf("Greeting: %s", r.Message)
}
```

输出结果:
```
2018/01/25 13:10:47 could not greet: rpc error: code = InvalidArgument desc = 我会说中国话
```
