### ISSUE TITLE
为什么执行sea new helloworld 报错呢？

### ISSUE THREAD

**Issue by a410202049** [shanbay/sea#132]
Traceback (most recent call last):
  File "d:\anaconda\envs\python3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\anaconda\envs\python3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\anaconda\envs\python3\Scripts\sea.exe\__main__.py", line 9, in <module>
  File "d:\anaconda\envs\python3\lib\site-packages\sea\cli.py", line 113, in main
    return _run(root)
  File "d:\anaconda\envs\python3\lib\site-packages\sea\cli.py", line 100, in _run
    return handler(**kwargs)
  File "d:\anaconda\envs\python3\lib\site-packages\sea\cmds.py", line 126, in new
    _gen_project(path, skip=_build_skip_files(extra), ctx=ctx)
  File "d:\anaconda\envs\python3\lib\site-packages\sea\cmds.py", line 114, in _gen_project
    tmpl = env.get_template(relfn)
  File "d:\anaconda\envs\python3\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "d:\anaconda\envs\python3\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "d:\anaconda\envs\python3\lib\site-packages\jinja2\loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "d:\anaconda\envs\python3\lib\site-packages\jinja2\loaders.py", line 168, in get_source
    pieces = split_template_path(template)
  File "d:\anaconda\envs\python3\lib\site-packages\jinja2\loaders.py", line 31, in split_template_path
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: app\extensions.py.tmpl

**Comment by zengzhengrong** [comment]
hi, I meet the same issues with new project by commd
"sea new --skip-peewee --skip-cache --skip-async_task --skip-bus --skip-sentry helloworld"
But There are noting return , Not any folder be created

below pip list

blinker         1.4      
grpcio          1.12.1   
grpcio-tools    1.12.1   
Jinja2          2.10.1   
MarkupSafe      1.1.1    
pendulum        2.0.5    
pip             19.2.3   
protobuf        3.10.0rc1
python-dateutil 2.8.0    
pytzdata        2019.2   
sea             2.0.0    
setuptools      41.2.0   
six             1.12.0   
wheel           0.33.6

**Comment by gukz** [comment]
@a410202049 @zengzhengrong  We will fix this problem soon.
